ansible/roles/vcs_store_bzr/defaults/main.yml
ansible/roles/vcs_store_git/defaults/main.yml

Fix ansible public ports

---

ansible/roles/base/tasks/main.yml
janitor/publish.py
janitor/site/queue.py
janitor/site/templates/cupboard/queue.html
janitor/state.py

Fix a remaining reference to suite in publish.

Fix a remaining reference to suite in publish

---

.gitignore
ansible/roles/base/tasks/main.yml
janitor/debian/archive.py
janitor/differ.py
janitor/publish.py
janitor/runner.py
janitor/site/queue.py
janitor/site/templates/cupboard/queue.html
janitor/state.py
janitor/vcs_store_bzr.py
janitor/vcs_store_git.py

Add /ready target

---

janitor/differ.py
janitor/publish.py
janitor/site/common.py
janitor/site/templates/cupboard/package-overview.html
janitor/site/templates/cupboard/run.html

Treat control and unchanged campaigns the same.

Treat control and unchanged campaigns the same

---

janitor/site/templates/cupboard/run.html

Round probablities

---

janitor/site/templates/cupboard/run.html
janitor/worker.py

Handle ConnectionReset in worker.

Handle ConnectionReset in worker

---

janitor/vcs_store_git.py

Handle old and new shas in vcs-store-git.

Handle old and new shas in vcs-store-git

---

janitor/runner.py
janitor/vcs_store_git.py

Only encode revision if present.

Only encode revision if present

---

janitor/vcs.py
janitor/vcs_store_git.py

Improve Git error handling

---

ansible/roles/irc_notify/templates/irc-notify.service

Fix irc_notify.py path for ansible.

Fix irc_notify.py path for ansible

---

janitor/site/queue.py
janitor/worker.py

Handle ConnectionReset, update dulwich/breezy.

Handle ConnectionReset, update dulwich/breezy

---

janitor/site/__init__.py
janitor/site/api.py
janitor/site/cupboard.py
janitor/site/review.py
janitor/site/templates/cupboard/sidebar.html
janitor/site/templates/cupboard/start.html
janitor/site/templates/review-stats.html

Add review stats page.
Allow anybody to review runs, but only QA reviewers opinion is considered before proposing/pushing.

Add review stats page

---

janitor/queue.py
janitor/site/queue.py

Fix queue handling

---

ansible/roles/worker/tasks/main.yml

ansible: Add missing pcre dependency.

ansible: Add missing pcre dependency

---

janitor/vcs.py

Implement local diff/revision-info.

Implement local diff/revision-info

---

Dockerfile_irc_notify
Dockerfile_mastodon_notify
Dockerfile_matrix_notify
Dockerfile_xmpp_notify
notifiers/matrix_notify.py

Fix matrix notify

---

Dockerfile_irc_notify
Dockerfile_mastodon_notify
Dockerfile_matrix_notify
Dockerfile_xmpp_notify
notifiers/matrix_notify.py

Update breezy, fix matrix-notify.

Update breezy, fix matrix-notify

---

janitor/publish.py

Fix import in publish

---

janitor/differ.py
janitor/publish_one.py
janitor/site/review.py
janitor/site/templates/cupboard/review-stats.html

Reacquire connections rather than keeping one open.

Reacquire connections rather than keeping one open

---

janitor/runner.py
janitor/vcs.py

Handle UnsupportedProtocol in --public-vcs-location

Handle UnsupportedProtocol in --public-vcs-location

---

janitor/site/api.py
state.sql

Add extra checks for vcs_type is null.

Add extra checks for vcs_type is null

---

Dockerfile_base

Install merge3

---

janitor/differ.py

Fix differ database access

---

janitor/differ.py

Update upstream-ontologist and other dependencies.
This should fix worker image builds.

Update upstream-ontologist and other dependencies

---

janitor/site/templates/cupboard/review-stats.html
janitor/site/templates/merge-proposal.html
janitor/vcs_store_git.py
janitor_client/__init__.py
notifiers/irc_notify.py
notifiers/mastodon_notify.py
notifiers/matrix_notify.py
notifiers/xmpp_notify.py

Fix compatibility with newer klaus.

Fix compatibility with newer breezy

---

Dockerfile_base
janitor/site/cupboard.py
janitor/site/review.py
janitor/site/templates/cupboard/sidebar.html
janitor/site/templates/cupboard/start.html
janitor/site/templates/cupboard/workers.html
janitor/vcs.py

Bunch of unrelated fixes, mostly improving error handling.

Bunch of unrelated fixes, mostly improving error handling

---

Dockerfile_base
Makefile
janitor/publish.py
janitor/site/review.py

Cope with missing branches for runs.

Cope with missing branches for runs

---

janitor/site/common.py
janitor/site/pkg.py

Add more checks for vcs_type being absent.

Add more checks for vcs_type being absent

---

.github/workflows/dockerimage-core.yaml
.github/workflows/dockerimage-worker.yaml
janitor/package_metadata.py

Create tags for git commit SHAs.

Create tags for git commit SHAs

---

Dockerfile_archive
Dockerfile_bzr_store
Dockerfile_git_store
Dockerfile_irc_notify
Dockerfile_mastodon_notify
Dockerfile_matrix_notify
Dockerfile_publish
Dockerfile_runner
Dockerfile_site
Dockerfile_worker
Dockerfile_xmpp_notify

Don't use recommends to keep images smaller.

Don't use recommends to keep images smaller

---

.github/workflows/pythonpackage.yml
Dockerfile_worker
janitor/site/api.py
janitor/site/common.py
state.sql

Various fixes

---

create-sbuild-chroot.py
janitor/publish.py
update-dependencies.sh

Add --chroot=unshare support

---

janitor/site/cupboard/__init__.py

Add /cupboard/run/{run} URL, redirecting to the right /cupboard/pkg/{pkg/{run_id} page.

Add /cupboard/run/{run} URL, redirecting to the right /cupboard/pkg/{pkg/{run_id} page

---

.github/workflows/pythonpackage.yml
Makefile
janitor/site/_static/basic.css

Color active entries on queue.

Color active entries on queue

---

Makefile
janitor/debian/__init__.py
janitor/tests/__init__.py
janitor/tests/test_debian.py
janitor/tests/test_vcs.py
janitor/worker.py

Improve and measure coverage

---

.github/workflows/pythonpackage.yml
Dockerfile_ognibuild_dep
Dockerfile_worker
Makefile
janitor/debian/__init__.py
janitor/debian/build.py
janitor/generic/build.py
janitor/publish.py
janitor/runner.py
janitor/site/cupboard/__init__.py

Add dep server

---

Dockerfile_worker
ansible/roles/base/templates/janitor.conf
janitor.conf.example
janitor/config.proto
janitor/runner.py

Refactor apt location, make runner argument.

Refactor apt location, make runner argument

---

.yamllint

Do some yaml linting

---

janitor/debian/build.py
janitor/runner.py
janitor/worker.py
state.sql

Track stage separately of result code.

Track stage separately of result code

---

janitor/debian/build.py
janitor/debian/missing_deps.py
janitor/missing_deps.py
janitor/publish_one.py
janitor/runner.py
janitor/vcs.py
janitor/worker.py
state.sql

Use dep server more

---

Makefile
ansible/roles/base/tasks/main.yml
ansible/roles/db/meta/main.yml
ansible/roles/irc_notify/tasks/main.yml
ansible/roles/mastodon_notify/tasks/main.yml
ansible/roles/site/tasks/main.yml
ansible/roles/worker/tasks/main.yml

Run yamllint

---

Makefile
janitor/tests/test_debdiff.py
janitor/tests/test_debian.py
janitor/tests/test_site.py
janitor/tests/test_vcs.py
setup.cfg
setup.py

the coverage and html-report is done automatically via setup.cfg, thus the makefile targes have been removed
closes #73

use pytest and pytest-cov

---

.github/workflows/pythonpackage.yml
setup.py

Fix dependencies in setup.py

---

janitor/publish.py

Fix some regressions in policy handling.

Fix some regressions in policy handling

---

janitor/publish.py
janitor/runner.py

Use default command when scheduling candidates

Use default command when scheduling candidates

---

janitor/publish.py

Support PUT for /policy

---

janitor/publish.py
janitor/site/common.py

Fix SQL query accessing runs

---

janitor/publish.py
janitor/site/common.py
janitor/state.py

Fix some SQL queries; regressions from policy refactor.

Fix some SQL queries; regressions from policy refactor

---

janitor/publish.py
janitor/runner.py

More fixes to the publish-policy refactor.

More fixes to the publish-policy refactor

---

janitor/runner.py

Fix handling of unknown publish policies.

Fix handling of unknown publish policies

---

janitor/publish.py
janitor/review.py
janitor/site/common.py
janitor/site/cupboard/__init__.py
janitor/site/cupboard/review.py
janitor/site/templates/cupboard/rejected.html
janitor/site/templates/cupboard/run.html
janitor/state.py
state.sql

Remove run.review_comment. Fixes #101

Remove run.review_comment

---

janitor/publish.py
janitor/site/api.py

Move core publish-details logic to publisher.

Move core publish-details logic to publisher

---

janitor/debian/archive.py
janitor/debian/auto_upload.py
janitor/differ.py
janitor/publish.py
janitor/runner.py
janitor/site/simple.py

Use redis pools

---

janitor/publish.py
janitor/review.py
janitor/runner.py
janitor/site/api.py
janitor/site/cupboard/__init__.py
janitor/site/cupboard/review.py

In particular, add /schedule and /schedule-control endpoints

Move some more logic to runner

---

setup.cfg

Update extra name for dep-server.

Update extra name for dep-server

---

janitor/review.py
janitor/site/api.py
janitor/site/cupboard/review.py
janitor/site/templates/cupboard/review.html
janitor/worker.py

Add finish_time on the review page

Add finish_time on the review page

---

janitor/publish.py
janitor/runner.py
janitor/tests/test_git_store.py
janitor/tests/test_runner.py
janitor/tests/test_worker.py
janitor/worker.py
setup.cfg

Add some more tests

---

janitor/site/pkg.py

Set timeout on publish-blockers requests

Set timeout on publish-blockers requests

---

janitor/debian/dist.py
janitor/runner.py
janitor/worker.py
state.sql

Track subpath

---

janitor/site/templates/cupboard/changeset.html

Include package in change set

---

janitor/debian/archive.py

Don't mark archive as ready until all releases have been published

Don't mark archive as ready until all releases have been published

---

state.sql

Only mark change_set as ready when there are successful runs

Only mark change_set as ready when there are successful runs

---

.github/workflows/pythonpackage.yml
janitor/runner.py
janitor/worker.py

Handle RemoteGitError during worker clone.

Handle RemoteGitError during worker clone

---

setup.cfg

Install new flake8

---

janitor/site/templates/cupboard/run.html
setup.cfg

Fix djlint

---

.github/workflows/container-worker.yaml
janitor/config.proto
janitor/debian/archive.py
janitor/debian/followup.py
janitor/debian/validate.py
janitor/runner.py
janitor/schedule.py
janitor/site/__init__.py
janitor/site/api.py
janitor/site/pkg.py
janitor/site/templates/cupboard/stats.html
janitor/site/templates/result-codes/branch-unavailable.html
janitor/worker.py
state.sql

Various improvements:
* Fix handling of per-package apt archives
* Support skip_setup_validation

Various improvements:

---

janitor/debian/archive.py
janitor/tests/test_archive.py

Fix size of Packages files in apt archive

Archive size

---

janitor/debian/archive.py
janitor/site/templates/run_util.html

Fix ordering when cleaning up archive items.

Fix ordering when cleaning up archive items

---

setup.cfg

Ship py.typed

---

janitor/bzr_store.py
janitor/debian/archive.py
janitor/differ.py
janitor/git_store.py
janitor/publish.py
janitor/runner.py
janitor/site/simple.py
janitor/state.py

Add middleware for returning 503s when database is having issues

Add middleware for returning 503s when database is having issues

---

.github/workflows/pythonpackage.yml
pyproject.toml
setup.cfg
setup.py

Install pb2 files

---

.github/workflows/container-core.yaml
.github/workflows/container-irc-notify.yaml
.github/workflows/container-mastodon-notify.yaml
.github/workflows/container-matrix-notify.yaml
.github/workflows/container-ognibuild-dep.yaml
.github/workflows/container-worker.yaml
.github/workflows/container-xmpp-notify.yaml
Dockerfile_archive
Dockerfile_base
Dockerfile_bzr_store
Dockerfile_differ
Dockerfile_git_store
Dockerfile_irc_notify
Dockerfile_mastodon_notify
Dockerfile_matrix_notify
Dockerfile_ognibuild_dep
Dockerfile_publish
Dockerfile_runner
Dockerfile_site
Dockerfile_worker
Dockerfile_xmpp_notify

Some image building refactoring:
* When building use base image from the same build
* Push for all feature branches
* Build notifiers in parallel

Some image building refactoring:

---

Dockerfile_base
Dockerfile_runner
pyproject.toml
setup.cfg

Add missing dependency on mypy-protobuf before setup is run

Add missing dependency on mypy-protobuf before setup is run

---

janitor/runner.py
state.sql

Explicitly track transientness for failures

Explicitly track transientness for failures

---

.containerignore
Dockerfile_git_store
Makefile
README.md
janitor/runner.py
janitor/worker.py
setup.cfg
tests/test_runner.py

Fix the runner - access to config variable

Fix the runner - access to config variable

---

Dockerfile_base
Dockerfile_worker
Makefile
helpers/migrate-logs.py
janitor/bzr_store.py
janitor/debian/archive.py
janitor/debian/build.py
janitor/debian/dist.py
janitor/differ.py
janitor/git_store.py
janitor/publish.py
janitor/queue.py
janitor/runner.py
janitor/schedule.py
janitor/site/api.py
janitor/site/pkg.py
janitor/site/simple.py
janitor/vcs.py
janitor/worker.py
state.sql

Various fixes:
* write multiple dist.log files. Fixes #94
* Set sample rate from 1.0 to 0.1
* don't return queue position in runner when scheduling

Various fixes:

---

.github/workflows/pythonpackage.yml
ansible/roles/archive/templates/archive.service
ansible/roles/auto_upload/templates/auto-upload.service
ansible/roles/base/defaults/main.yml
ansible/roles/base/tasks/main.yml
ansible/roles/base/templates/env
ansible/roles/bzr_store/templates/bzr-store.service
ansible/roles/differ/templates/differ.service
ansible/roles/git_store/templates/git-store.service
ansible/roles/irc_notify/templates/irc-notify.service
ansible/roles/mastodon_notify/templates/mastodon-notify.service
ansible/roles/ognibuild_dep/templates/ognibuild-dep.service
ansible/roles/publish/templates/publish.service
ansible/roles/runner/templates/run.service
ansible/roles/site/templates/site.service
ansible/roles/worker/tasks/main.yml
ansible/roles/worker/templates/worker@.service

Refactor ansible to use pip

---

janitor/debian/dist.py
janitor/debian/missing_deps.py
janitor/generic/build.py
janitor/publish.py
janitor/runner.py
janitor/site/api.py
janitor/site/pkg.py
janitor/vcs.py
janitor/worker.py
setup.cfg

Update some import as code is being moved between lintian-brush and ognibuild

Update some import as code is being moved between lintian-brush and ognibuild

---

Dockerfile_worker
janitor/debian/build.py
janitor/generic/build.py
janitor/publish.py
janitor/worker.py

Plumb through stages

---

Dockerfile_worker
apt-package-metadata.py
janitor/debian/build.py
janitor/generic/build.py
janitor/package_metadata.proto
janitor/package_metadata.py
janitor/publish.py
janitor/runner.py
janitor/site/webhook.py
janitor/worker.py
state.sql

Also store repository URL and branch separately.

Also store repository URL and branch separately

---

Dockerfile_base
Dockerfile_irc_notify
Dockerfile_mastodon_notify
Dockerfile_matrix_notify
Dockerfile_ognibuild_dep
Dockerfile_publish
Dockerfile_worker
Dockerfile_xmpp_notify
README.md

Move docker images over to using testing as base

Move docker images over to using testing as base

---

Dockerfile_worker
janitor/missing_deps.py
setup.cfg

Drop lintian-brush from dependencies.
It's no longer used directly by the janitor itself.

Drop lintian-brush from dependencies

---

janitor/package_metadata.py
janitor/runner.py

Only set codebase name in package when there is a codebase

Only set codebase name in package when there is a codebase

---

janitor/debian/dist.py
janitor/site/cupboard/review.py
janitor/worker.py

Fix syntax of SQL query for rejected runs.

Fix syntax of SQL query for rejected runs

---

setup.cfg

Install janitor.generic

---

.github/workflows/pythonpackage.yml
Dockerfile_runner
Dockerfile_worker
ansible/roles/base/tasks/main.yml
setup.cfg

Use system python3-apt

---

ansible/roles/worker/templates/worker@.service
setup.cfg

Several fixes for ansible setup
* Install cupboard
* Fix worker systemd file

Several fixes for ansible setup

---

helpers/migrate-logs.py
setup.cfg

Ban some modules with flake8

---

ansible/roles/worker/tasks/main.yml
create-sbuild-chroot-schroot.py

Some improvements for the kali janitor:
* refactor handling of chroots in ansible
* avoid shlex.join, not available on older pythons

Some improvements for the kali janitor:

---

janitor/publish.py
janitor/publish_one.py

Plumb through title template

---

janitor/publish.py

Handle ForeignKeyViolations when deleting named policies.

Handle ForeignKeyViolations when deleting named policies

---

janitor/publish.py
janitor/schedule.py
janitor/site/__init__.py
janitor/site/common.py
janitor/site/cupboard/__init__.py
janitor/site/templates/run_util.html
state.sql

Use the failure_transient field

Use the failure_transient field

---

janitor/publish.py
janitor/site/common.py
janitor/site/cupboard/review.py
janitor/site/pkg.py
janitor/site/templates/cupboard/result-code.html
janitor/state.py

Report stage in result_code pages

Report stage in result_code pages

---

janitor/publish.py

Add a /absorbed endpoint to publisher

Add a /absorbed endpoint to publisher

---

ansible/roles/base/tasks/main.yml
ansible/roles/publish/tasks/creds.yml
ansible/tasks/reprocess_logs.yml
janitor/config.proto
janitor/runner.py
janitor/worker.py

Add "default_empty" setting

---

.github/workflows/sql.yaml

Run tests against installed postgres.

Run tests against installed postgres

---

janitor/debian/dist.py

Fix import of run-apt

---

CONTRIBUTING.md
tests/test_dist.py

Update CONTRIBUTING.md, add basic dist test

Update CONTRIBUTING.md, add basic dist test

---

janitor/missing_deps.py
janitor/publish.py
janitor/queue.py
janitor/schedule.py
state.sql

Add codebase to queue, and populate it

Add codebase to queue, and populate it

---

janitor/site/simple.py
setup.cfg

Install dulwich from git, fix path to done.html

Install dulwich from git, fix path to done.html

---

janitor/site/cupboard/__init__.py
janitor/site/pkg.py
janitor/site/simple.py
janitor/site/templates/cupboard/done-list.html
janitor/site/templates/cupboard/sidebar.html
setup.cfg

Add done to cupboard

---

Dockerfile_ognibuild_dep

Fix spelling of dep_server extra.

Fix spelling of dep_server extra

---

janitor/bzr_store.py
janitor/diffoscope.py
janitor/publish.py
janitor/site/__init__.py
janitor/site/cupboard/__init__.py
janitor/site/cupboard/review.py
janitor/site/simple.py
janitor/state.py
reschedule.py
state.sql

Rename suite to campaign in a few more places

Rename suite to campaign in a few more places

---

janitor/publish_one.py

Support 429 http response codes in publisher

Support 429 http response codes in publisher

---

debian.sql
janitor/debian/archive.py

Use debian_build rather than package in janitor.debian.archive

Use debian_build rather than package in janitor.debian.archive

---

Dockerfile_ognibuild_dep
state.sql

Include revision in absorbed_runs

Include revision in absorbed_runs

---

Dockerfile_ognibuild_dep

Add missing dependency on debian extra in ognibuild-dep-server container

Add missing dependency on debian extra in ognibuild-dep-server container

---

janitor/site/cupboard/__init__.py
janitor/site/pkg.py
janitor/site/simple.py
janitor/site/templates/cupboard/done-list.html
janitor/site/templates/generic/done.html
state.sql

Improve done pages

---

janitor/git_store.py
janitor/site/api.py
janitor/site/pkg.py
janitor/worker.py

Drop some backwards compatibility code.

Drop some backwards compatibility code

---

janitor/site/cupboard/__init__.py
janitor/site/pkg.py

Sort nulls last on done page

---

janitor/site/cupboard/__init__.py
janitor/site/pkg.py
janitor/site/templates/cupboard/done-list.html
janitor/site/templates/generic/done.html

Improve formatting for done page.

Improve formatting for done page

---

janitor/schedule.py

Allow values for candidates to be zero

Allow values for candidates to be zero

---

janitor/publish.py
tests/test_publish.py

Fix finding of campaign by branch name.

Fix finding of campaign by branch name

---

CONTRIBUTING.md
janitor/site/templates/cupboard/done-list.html
janitor/site/templates/generic/done.html
state.sql

Add merge proposal link

---

janitor/publish.py

Fix publish policy deletion

---

janitor/mail_filter.py
setup.cfg
sieve/janitor.sieve

Integrate mail filter into janitor namespace

Integrate mail filter into janitor namespace

---

janitor/runner.py

Fix queue position calculation

Fix queue position calculation

---

janitor/package_metadata.py

Fix package metadata db access.

Fix package metadata db access

---

janitor/publish.py

Drop half-broken docs stuff that's breaking kali.

Drop half-broken docs stuff that's breaking kali

---

janitor/publish.py
tests/test_publish.py

Prevent loops in the publisher due to orphaned MPs.

Prevent loops in the publisher due to orphaned MPs

---

janitor/publish.py
janitor/runner.py
janitor/site/cupboard/review.py
janitor/site/openid.py
janitor/site/templates/cupboard/run.html
notifiers/mastodon_notify.py
notifiers/matrix_notify.py

Various kali-related fixes

---

janitor/site/templates/cupboard/run.html

Clarify wording around binary diffs
Fixes kali janitor issue #10

Clarify wording around binary diffs

---

janitor/site/templates/cupboard/run.html

Move review status drop down to bottom of page

Move review status drop down to bottom of page

---

setup.cfg

Install create-sbuild-chroot scripts

Install create-sbuild-chroot scripts

---

janitor/runner.py
janitor/schedule.py
janitor/worker.py

Several minor fixes:
* Fix scheduling of no-vcs packages
* Fix formatting of worker pages

Several minor fixes:

---

janitor/publish.py

Handle CandidateUnavailable when checking existing MPs.

Handle CandidateUnavailable when checking existing MPs

---

janitor/site/templates/cupboard/run.html

Fix namespace handling

---

janitor/missing_deps.py
janitor/runner.py
janitor/site/templates/cupboard/run.html

Various small improvements
* Handle incomplete upstream info.
* Fix review comment display.
* None doesn't have a get method.
* Handle missing queue item.

Various small improvements

---

janitor/debian/archive.py
janitor/debian/auto_upload.py
janitor/differ.py
janitor/publish.py
janitor/runner.py
janitor/site/simple.py
setup.cfg
tests/test_publish.py
tests/test_runner.py

Migrate from aioredis to redis.

Migrate from aioredis to redis

---

janitor/debian/archive.py
janitor/debian/auto_upload.py
janitor/differ.py
janitor/publish.py
janitor/site/simple.py

Fix redis interaction

---

janitor/runner.py

Fix pipeline handling in redis

Fix pipeline handling in redis

---

README.md
janitor/worker.py
tests/test_publish.py
tests/test_worker.py

Push changes early

---

janitor/missing_deps.py
janitor/publish.py
janitor/reprocess_logs.py
janitor/schedule.py
janitor/worker.py

* Use routes for HTTP targets
* Include run id in title

Various worker refactorings

---

janitor/runner.py
janitor/site/common.py
janitor/worker.py

Fix codebase passthrough

---

janitor/queue.py

Drop package alias for codebase.

Drop package alias for codebase

---

janitor/worker.py

This is affecting a lot of the kali builds.

Prevent overlap in tags

---

janitor/bzr_store.py
janitor/git_store.py
janitor/package_metadata.py
janitor/publish.py
janitor/review.py
janitor/schedule.py
janitor/site/__init__.py
janitor/site/api.py
janitor/site/common.py
janitor/site/cupboard/__init__.py
janitor/site/cupboard/queue.py
janitor/site/cupboard/review.py
janitor/site/simple.py
janitor/site/templates/cupboard/changeset.html
janitor/site/templates/cupboard/history.html
janitor/site/templates/cupboard/publish-history.html
janitor/site/templates/cupboard/publish.html
janitor/site/templates/cupboard/queue.html
janitor/site/templates/cupboard/result-code-index.html
janitor/site/templates/cupboard/run.html
janitor/site/templates/cupboard/workers.html
janitor/site/templates/generic/package.html
janitor/worker.py

Use aiohttp-jinja2

---

janitor/site/api.py
janitor/site/common.py
janitor/site/simple.py

Fix jinja2, make things easier to patch out in unit tests.

Fix jinja2, make things easier to patch out in unit tests

---

janitor/site/cupboard/__init__.py
janitor/site/templates/cupboard/result-code-index.html

Add include_historical checkbox

---

janitor/config.py
janitor/vcs.py
janitor/worker.py
tests/test_bzr_store.py
tests/test_config.py
tests/test_core.py
tests/test_runner.py
tests/test_vcs.py
tests/test_worker.py

Add more tests

---

Dockerfile_archive
Dockerfile_bzr_store
Dockerfile_differ
Dockerfile_git_store
Dockerfile_publish
Dockerfile_runner
Dockerfile_worker

Install missing libgpg-error-dev

Install missing libgpg-error-dev

---

janitor/debian/archive.py
janitor/publish.py

Fix some SQL errors

---

janitor/runner.py

Fix backchannel handling

---

janitor/worker.py

Create git dir if it doesn't exist.

Create git dir if it doesn't exist

---

janitor/debian/build.py
janitor/debian/dist.py
janitor/worker.py
tests/test_worker.py

These changes are complete, but we may want to hold off for a while until there are more places where e.g. stage is shown.

Simplify result codes, dropping stage

---

janitor/runner.py

Bump priority when changing command of active PRs
Fixes #352

Bump priority when changing command of active PRs

---

janitor/debian/archive.py
janitor/publish.py
janitor/runner.py

Fix /ready for archive

---

janitor/site/pkg.py
janitor/site/templates/cupboard/run.html

Display followup runs

---

janitor/publish.py
janitor/site/pkg.py

Populate merged-by-url

---

janitor/site/common.py

Fix iter_candidates SQL query

---

janitor/publish.py

Refactor publish a bit; use last_effective_runs table, handle more exceptions

Refactor publish a bit; use last_effective_runs table, handle more exceptions

---

janitor/publish.py

Handle PermissionDenied when scanning for stragglers

Handle PermissionDenied when scanning for stragglers

---

janitor/publish.py
janitor/runner.py
state.sql

publish: Cope with missing runs

publish: Cope with missing runs

---

janitor/site/cupboard/review.py
janitor/site/templates/cupboard/review.html
janitor/site/templates/lintian_util.html

Cope with lintian-result JSON output differences

Cope with lintian-result JSON output differences

---

janitor/publish.py
janitor/site/cupboard/merge_proposals.py
janitor/site/templates/cupboard/merge-proposal.html
state.sql

Add run_id field to publish

---

janitor/runner.py
janitor/site/simple.py

Fix runner candidate query

---

janitor/runner.py

Add prefix for public runner API

Add prefix for public runner API

---

janitor/runner.py

runner: Add active runs info to public API

runner: Add active runs info to public API

---

janitor/site/api.py

Fix include-transient for mass-reschedule

Fix include-transient for mass-reschedule

---

janitor/runner.py
tests/test_runner.py

Add more typing for run

---

janitor/differ.py

Refactor differ a bit

---

janitor/differ.py
janitor/diffoscope.py

Support running diffoscope in podman

Support running diffoscope in podman

---

janitor/site/api.py

Handle bad regexes during mass-reschedule

Handle bad regexes during mass-reschedule

---

janitor/publish.py
janitor/site/templates/run_util.html

Consider actions on older merge proposals

---

janitor/runner.py

Allow modifying followups table from /candidates

Allow modifying followups table from /candidates

---

janitor/runner.py

Add some spans for POST /candidates

Add some spans for POST /candidates

---

janitor/runner.py
janitor/site/api.py
janitor/site/common.py
janitor/vcs.py

Pass trace configs along

---

janitor/differ.py

differ: Add some more spans

---

janitor/artifacts.py
janitor/runner.py

Upload logs in parallel

---

janitor/bzr_store.py
janitor/debian/archive.py
janitor/differ.py
janitor/git_store.py
janitor/mail_filter.py
janitor/publish.py
janitor/runner.py
janitor/site/simple.py
janitor/worker.py
setup.cfg

Use uvloop

---

janitor/worker.py
tests/test_worker.py

Clarify result code for exit code 137

Clarify result code for exit code 137

---

janitor/differ.py

Make differ arguments optional

Make differ arguments optional

---

janitor/publish.py
state.sql

Try harder to avoid re-publishing.

Try harder to avoid re-publishing

---

janitor/publish.py
janitor/publish_one.py
janitor/vcs.py
setup.cfg
tests/test_vcs.py

Avoid unnecessary dependency on upstream-ontologist.

Avoid unnecessary dependency on upstream-ontologist

---

janitor/publish.py
janitor/worker.py

Skip role=main colocated branches

Skip role=main colocated branches

---

janitor/site/cupboard/__init__.py
janitor/site/simple.py

Fix /cupboard/api attachment

---

janitor/site/pkg.py

Cope with missing suite

---

janitor/site/cupboard/review.py
setup.cfg

Retrieve missing campaign

---

setup.cfg

Rely on released asyncpg-engine

Rely on released asyncpg-engine

---

janitor/site/templates/cupboard/evaluate.html
setup.cfg

Add evaluate template

---

janitor/site/templates/cupboard/review.html

More evaluate fixes

---

janitor/site/templates/cupboard/review.html
tests/test_runner.py

Add more runner tests

---

janitor/site/api.py
janitor/site/cupboard/__init__.py
janitor/site/cupboard/api.py

Allow overriding database, for tests.

Allow overriding database, for tests

---

janitor/site/cupboard/review.py

review: Fix http-only warning.

review: Fix http-only warning

---

janitor/site/cupboard/__init__.py

review: Fix non-JS path

---

janitor/publish.py
janitor/site/templates/cupboard/review.html
janitor/site/templates/run_util.html

publish: Fix checking for previous MPs.

publish: Fix checking for previous MPs

---

janitor/publish.py

publis: Fix get_previous_mp_status return type.

publis: Fix get_previous_mp_status return type

---

janitor/publish.py

publish: Improve query for finding previous MPs.

publish: Improve query for finding previous MPs

---

janitor/publish.py

publish: Add new merge proposal counter

publish: Add new merge proposal counter

---

janitor/publish.py

publish: Improve logging

---

janitor/site/templates/cupboard/review.html

review: Set preload for review to 20

review: Set preload for review to 20

---

janitor/publish.py

publish: don't bother if revision hasn't changed

publish: don't bother if revision hasn't changed

---

janitor/site/templates/cupboard/merge-proposal.html

Add refresh button on merge proposal page

Add refresh button on merge proposal page

---

janitor/site/cupboard/__init__.py
janitor/state.sql

cupboard: have done page default to since of beginning of the month.

cupboard: have done page default to since of beginning of the month

---

janitor/queue.py
janitor/runner.py
janitor/site/api.py
janitor/site/common.py
janitor/site/cupboard/review.py
janitor/site/pkg.py
janitor/site/templates/cupboard/default-evaluate.html
janitor/state.sql
tests/test_runner.py

Stop consulting package field in queue.

Stop consulting package field in queue

---

janitor/publish.py
janitor/publish_one.py
tests/test_publish.py

Simplify publish_one

---

janitor/logs.py
janitor/publish.py
janitor/queue.py
janitor/runner.py
janitor/schedule.py
janitor/site/cupboard/__init__.py
janitor/site/cupboard/api.py
janitor/site/simple.py
janitor/state.py
janitor/state.sql
janitor/vcs.py
tests/test_publish.py
tests/test_runner.py
tests/test_vcs.py

Remove package from the API in various places

More cleanups

---

janitor/site/common.py

QUery codebase for cupboard package overview.

Query codebase for cupboard package overview

---

janitor/review.py
janitor/site/api.py

* Drop unused API calls
* Fixing when storing reviews

Various improvements

---

janitor/runner.py

Reserialize active run, to pick up changed attributes
Fixes #402

Reserialize active run, to pick up changed attributes

---

janitor/runner.py

Return JSON for 404s

---

janitor/queue.py

Handle queue not changing in Queue.add

Handle queue not changing in Queue.add

---

janitor/publish_one.py

publish_one: fall back to markdown if regular text is not available

publish_one: fall back to markdown if regular text is not available

---

janitor/schedule.py

Improve schedule error message

Improve schedule error message

---

janitor/runner.py

Read vcs type information from worker

Read vcs type information from worker

---

janitor/site/__init__.py
janitor/site/cupboard/__init__.py
janitor/site/templates/cupboard/history.html
janitor/site/templates/cupboard/queue.html
janitor/site/templates/cupboard/run.html
tests/test_cupboard.py

site: Don't link to private workers

site: Don't link to private workers

---

janitor/queue.py
janitor/runner.py
janitor/state.sql

sql: Use codebase rather than package

sql: Use codebase rather than package

---

tests/test_git_store.py

Add some tests for git-store diffs

Add some tests for git-store diffs

---

janitor/schedule.py

Various robustness fixes

---

janitor/logs.py

Fix logs exception type: PermissionDenied => PermissionError.

Fix logs exception type: PermissionDenied => PermissionError

---

janitor/queue.py

Add assert message

---

janitor/schedule.py
janitor/site/pkg.py

Integrate success and duration determination, improving performance
See #522

Integrate success and duration determination, improving performance

---

janitor/publish.py

Avoid querying unused column branch_name

Avoid querying unused column branch_name

---

janitor/publish.py
janitor/state.sql

Fix control run iteration

---

janitor/publish.py

publish: Retrieve missing field value

publish: Retrieve missing field value

---

janitor/publish.py

Ignore runs without publish policy

Ignore runs without publish policy

---

janitor/publish.py
janitor/runner.py

Fix auto publish

---

janitor/publish.py
janitor/review.py
janitor/runner.py
janitor/site/api.py
janitor/site/cupboard/__init__.py

Update publish status via runner

Update publish status via runner

---

janitor/publish.py

Revert removal of --no-auto-publish flag

Revert removal of --no-auto-publish flag

---

janitor/site/common.py

Query candidate by codebase

---

janitor/debian/archive.py
janitor/site/common.py

Properly populate apt repositories where build_distribution!=name

Properly populate apt repositories where build_distribution!=name

---

janitor/site/common.py

Drop package from iter_candidates response

Drop package from iter_candidates response

---

janitor/runner.py
janitor/state.sql

Remove more uses of candidate.package

Remove more uses of candidate.package

---

janitor/schedule.py

Fetch start_time for IGNORE_CHECKER when scheduling

Fetch start_time for IGNORE_CHECKER when scheduling

---

janitor/queue.py

Fix retrieval of queue items when change_set=NULL

Fix retrieval of queue items when change_set=NULL

---

tests/test_queue.py

Add queue test

---

janitor/runner.py
janitor/state.sql
tests/test_runner.py

Restructure ping handling in runner

Restructure ping handling in runner

---

janitor/debian/archive.py
janitor/differ.py
janitor/publish.py
janitor/site/cupboard/api.py
setup.cfg

Use aiojobs for background work

Use aiojobs for background work

---

janitor/logs.py

logs: Allow separately overriding target basename

logs: Allow separately overriding target basename

---

janitor/runner.py
tests/test_runner.py

Reschedule runs in the background

Reschedule runs in the background

---

janitor/runner.py
janitor/state.sql
tests/test_runner.py

Avoid repeatedly retrieving codebase and named policies

Avoid repeatedly retrieving codebase and named policies

---

janitor/queue.py
tests/test_queue.py

Fix a typo in cast

---

janitor/queue.py
janitor/runner.py
janitor/worker.py
tests/test_queue.py
tests/test_runner.py

Pass vcs_type along to worker, even if branch_url is empty

Pass vcs_type along to worker, even if branch_url is empty

---

janitor/queue.py
janitor/schedule.py

Fix queue query quoting

---

janitor/site/common.py

Actually retrieve publish_status

Actually retrieve publish_status

---

janitor/bzr_store.py
tests/test_bzr_store.py

Initialize bzr store jail

---

README.md
devnotes/overview.rst
janitor/publish.py
janitor/site/templates/faq-auto-push.html
janitor/site/templates/result-codes/control-file-is-generated.html

-------8<-------
SUMMARY:
entires       1
existance     1
permision     1
succesful     3
succesfully   1

Fix some spelling errors

---

tests/test_artifacts.py
tests/test_differ.py
tests/test_publish.py
tests/test_vcs.py

Upgrade code to a modern version (3.x+)

Upgrade code to a modern version (3.x+)

---

create-sbuild-chroot-schroot.py

Add --run-command

---

create-sbuild-chroot-schroot.py

Encode command to run in schroot

Encode command to run in schroot

---

create-sbuild-chroot-schroot.py

create-schroot: Fix error reporting when running commands

create-schroot: Fix error reporting when running commands

---

create-sbuild-chroot-schroot.py
janitor/worker.py

run_worker no longer returns anything

run_worker no longer returns anything

---

devnotes/adding-a-new-campaign.rst
janitor.conf.example
janitor/config.proto
janitor/config.py
janitor/debian/archive.py
tests/test_config.py

Add apt_repository stanza

---

janitor/runner.py

Cope with missing build details

Cope with missing build details

---

janitor/debian/archive.py
janitor/publish.py
janitor/state.sql
tests/test_publish.py

Drop dry-run command, make codebase non-optional

Drop dry-run command, make codebase non-optional

---

janitor/publish.py
janitor/site/cupboard/publish.py
janitor/site/templates/cupboard/publish-history.html
janitor/site/templates/cupboard/publish.html
janitor/state.sql

Drop publish.package

---

janitor/debian/archive.py
janitor/site/cupboard/__init__.py
janitor/site/cupboard/review.py
janitor/site/templates/cupboard/review.html
janitor/state.sql

Avoid more uses of run.package

Avoid more uses of run.package

---

janitor/debian/archive.py

Fix /ready for publish

---

janitor/site/templates/cupboard/broken-merge-proposals.html
janitor/site/templates/cupboard/never-processed.html
janitor/site/templates/cupboard/publish-history.html
janitor/site/templates/cupboard/queue.html
janitor/site/templates/cupboard/result-code.html
janitor/site/templates/fresh-util.html
janitor/site/templates/generic/candidates.html
janitor/site/templates/inputs.html

Use package rather than codebase in UI

Use package rather than codebase in UI

---

janitor/site/cupboard/publish.py

Fix join type on publish page

---

janitor/publish.py
janitor/site/cupboard/__init__.py
janitor/site/cupboard/review.py
janitor/site/templates/cupboard/review.html

Fix review selection

---

janitor/site/templates/run_util.html
tests/test_site_macros.py

Handle inactive publish blocker

Handle inactive publish blocker

---

Dockerfile_git_store
Dockerfile_worker
janitor/state.sql

Drop debian-janitor-specific distribution_name

Drop debian-janitor-specific distribution_name

---

janitor/publish.py
janitor/site/cupboard/__init__.py
janitor/site/cupboard/publish.py
janitor/state.sql

Add publish.target_branch_web_url

Add publish.target_branch_web_url

---

janitor/site/cupboard/__init__.py
janitor/site/cupboard/publish.py
janitor/site/simple.py
tests/test_cupboard.py

Fix publish page, add tests

---

janitor/site/openid.py

openid: Request email + profile scope

openid: Request email + profile scope

---

janitor/site/openid.py

Fix openid scope seperator

---

janitor/runner.py

Handle SSLZeroReturnError

---

TODO.rust
crates/runner/Cargo.toml
crates/runner/src/lib.rs
crates/runner/src/queue.rs

Add runner crate

---

Dockerfile_ognibuild_dep
create-sbuild-chroot-schroot.py
create-sbuild-chroot-unshare.py
helpers/cleanup-repositories.py
helpers/migrate-logs.py
janitor/debian/archive.py
janitor/debian/debdiff.py
janitor/differ.py
janitor/git_store.py
janitor/runner.py
janitor/schedule.py
janitor/site/api.py
janitor/site/common.py
janitor/site/cupboard/__init__.py
janitor/site/cupboard/merge_proposals.py
janitor/site/cupboard/queue.py
janitor/site/cupboard/review.py
janitor/site/merge_proposals.py
janitor/site/pkg.py
janitor/site/pubsub.py
janitor/site/simple.py
janitor/site/webhook.py
janitor/vcs.py
janitor/worker.py
pyproject.toml
tests/conftest.py
tests/test_runner.py

Run pyupgrade in ruff

---

Cargo.lock
Cargo.toml
src/config.rs
src/lib.rs
src/state.rs

Add state file in rust

---

src/state.rs

Support setting database settings through environment

Support setting database settings through environment

---

janitor/worker.py

Fix worker URL conversion

---

janitor/publish.py

Convert URLs to strings for postgres

Convert URLs to strings for postgres

---

Cargo.lock
Cargo.toml
src/lib.rs

Add logging initialization function

Add logging initialization function

---

Cargo.lock
Cargo.toml
src/config.rs
src/lib.rs
src/publish.rs

Add some json definitions

---

.github/workflows/pythonpackage.yml
Makefile

Use PYTHON environment variable in github action

Use PYTHON environment variable in github action

---

.gitignore
.testr.conf

Add testrepository configuration

Add testrepository configuration

---

.codespell-ignore-words
.github/workflows/pythonpackage.yml
Cargo.lock
crates/mail-filter/src/bin/janitor-mail-filter.rs
crates/mail-filter/src/lib.rs
crates/mail-filter/src/tests.rs
crates/worker-py/src/lib.rs
crates/worker/Cargo.toml
crates/worker/src/bin/worker.rs
crates/worker/src/debian/mod.rs
crates/worker/src/lib.rs
janitor/publish.py
janitor/queue.py
janitor/reprocess_logs.py
janitor/review.py
janitor/runner.py
janitor/schedule.py
janitor/site/api.py
janitor/site/cupboard/api.py
janitor/site/pkg.py
janitor/site/simple.py
janitor/site/templates/cupboard/queue.html
janitor/site/templates/cupboard/run.html
janitor/site/templates/result-codes/command-failed.html
janitor/state.sql
pyproject.toml
setup.py

Fix issues reported by clippy and codespell.

Fix issues reported by clippy and codespell

---

Cargo.lock
Cargo.toml
Dockerfile_site
crates/worker/src/lib.rs

Bump versions

---

.github/workflows/pythonpackage.yml
pyproject.toml

Bumping python versions in GitHub workflows and pyproject.toml
* Updated the requires-python field in pyproject.toml to ['3.12', '3.13']
* Updated the python-version in .github/workflows/pythonpackage.yml

Bumping python versions in GitHub workflows and pyproject.toml

---

publish/src/bin/janitor-publish.rs

Fix spelling errors
Used config files:
1: .codespellrc
-------8<-------
SUMMARY:
chnages       1

Fix spelling errors

---

.github/workflows/sql.yaml

Cherry picked from https://github.com/jelmer/janitor/pull/907

Update SQL workflows

---

pyproject.toml

Follow on from https://github.com/jelmer/janitor/pull/927

Update PyProject.toml (#2)

---

py/janitor/site/__init__.py

Fix duration test

---

janitor.conf.example
mail-filter/tests/data/github-merged-email.txt
py/janitor/git_store.py
py/janitor/site/templates/webhook.html
py/janitor/worker_creds.py

Janitor / Janitor Bot: https://github.com/jelmer/janitor ([salsa](https://salsa.debian.org/jelmer/janitor))
Debian Janitor: https://salsa.debian.org/janitor-team/janitor.debian.net

Debian Janitor -> Janitor Bot

---

py/janitor/runner.py

REF: https://github.com/jelmer/janitor/pull/972#pullrequestreview-2660900542

Runner: Clean up public port wording

---

create-sbuild-chroot-schroot.py
create-sbuild-chroot-unshare.py
helpers/migrate-logs.py
helpers/render-publish-template.py
py/janitor/bzr_store.py
py/janitor/debian/archive.py
py/janitor/debian/auto_upload.py
py/janitor/differ.py
py/janitor/git_store.py
py/janitor/publish.py
py/janitor/runner.py
py/janitor/schedule.py
py/janitor/site/simple.py
reprocess-build-results.py
reschedule.py

REF: https://github.com/jelmer/janitor/pull/955#discussion_r1977449822

Check --config path

---

Dockerfile_worker
docs/Dockerfiles_.md
worker/src/bin/worker.rs

https://github.com/jelmer/janitor/issues/958
https://github.com/jelmer/janitor/issues/959

Worker improvements

---

worker/src/client.rs
worker/src/lib.rs

Handle errors when dpkg-architecture is missing

---

runner/src/main.rs

```
$ grep -Ri new_port .
./runner/src/main.rs:    let addr = SocketAddr::new(args.listen_address, args.new_port);
$ 
$ grep -Ri new-port .
$
```

Runner: new_port -> port

---

py/janitor/runner.py

I know its not the cleanest solution, but working

Fix #1029 - Runner: Drop trace_configs

---

.github/workflows/containers.yaml

github.repository_owner is the best variable, but it gets confused with who the owner if when doing a PR.

CI: Fix trying to push on pull_request
