ansible/roles/worker/tasks/main.yml
cronic will catch output and will print it only if it detects output on stderr or if the command returned with a non-zero exit status.
That way admins get a mail only when something has gone wrong.
=> Don't spam admins with sbuild-update output when things go well

janitor/package_metadata.py, janitor/reprocess_logs.py, janitor/schedule.py, janitor/tests/__init__.py
this pr removes all traces of Python2 support, namely the `__future__.absolute_import` which is not needed in the supported python3 versions.
=> removed old traces of python2 support

setup.cfg
Use consistent URL for python_apt in setup.cfg.
=> Use consistent URL for python_apt in setup.cfg

janitor/runner.py, janitor/site/api.py, janitor/site/cupboard/publish.py, janitor/site/templates/cupboard/run.html, janitor/worker.py
Various fixes:
* Fix encoding for default-empty.
* Allow rescheduling non-vcs packages.
* Don't show reviews for failed runs.
* Show 404 when publish link is invalid.
* Handle empty cumulative_wait_time.
=> Various fixes:

create-sbuild-chroot-schroot.py
Use sbuild-shell to permanently create home directory
=> Use sbuild-shell to permanently create home directory

janitor/publish.py, setup.cfg, tests/test_publish.py
Previously, we'd still update them but wouldn't create them if they didn't have a high enough value to start with.
Fixes #251
=> Close merge proposals once their value falls below threshold

janitor/publish.py, janitor/site/templates/run_util.html
Don't mark branches as absorbed if the publish action wasn't successful
Fixes #327
=> Don't mark branches as absorbed if the publish action wasn't successful

janitor/runner.py, janitor/worker.py
Add assert for nothing-new-to-do when there is no resume branch
=> Add assert for nothing-new-to-do when there is no resume branch

janitor/state.sql
Drop unnecessary constraint for run; it's possible to have VCS-less runs.
=> Drop unnecessary constraint for run; it's possible to have VCS-less runs

janitor/differ.py, janitor/runner.py, janitor/site/cupboard/api.py
python3.11 compat: Don't pass coroutines to asyncio.wait
=> python3.11 compat: Don't pass coroutines to asyncio.wait

janitor/publish.py
Fix a call to .fetchrow
I'm not sure how this ever worked; perhaps [0] on a list of rows used to return
the first cell of the first row?
=> Fix a call to .fetchrow

janitor/site/cupboard/api.py
Avoid querying package when mass-rescheduling
=> Avoid querying package when mass-rescheduling

janitor/debian/build.py
Construct fixers in janitor.debian.build, ahead of ognibuild refactoring
=> Construct fixers in janitor.debian.build, ahead of ognibuild refactoring

janitor/site/cupboard/__init__.py
Fix cupboard run URLs, consistently use /c/
=> Fix cupboard run URLs, consistently use /c/

janitor/runner.py, janitor/vcs.py, janitor/worker.py, pyproject.toml
=> Fix some tests

worker/Cargo.toml
```console
$ cargo clean; RUSTFLAGS=-Awarnings cargo build --manifest-path worker/Cargo.toml
Removed 5344 files, 3.0GiB total
Compiling proc-macro2 v1.0.92
Compiling unicode-ident v1.0.14
[...]
Compiling askama_axum v0.4.0
Compiling ognibuild v0.0.32 (https://github.com/jelmer/ognibuild.git#0a5e3772)
Compiling janitor-worker v0.0.0 (/tmp/janitor/worker)
error[E0308]: mismatched types
--> worker/src/web.rs:54:5
|
30 |   async fn index(State(state): State<Arc<RwLock<AppState>>>) -> Response {
|                                                                 -------- expected `axum::http::Response<axum::body::Body>` because of return type
...
54 | /     IndexTemplate {
55 | |         assignment: state.assignment.as_ref(),
56 | |         lognames,
57 | |         metadata: …
```
=> Downgrade worker's axum@0.7.9

create-sbuild-chroot-schroot.py, create-sbuild-chroot-unshare.py, reprocess-build-results.py, reschedule.py, setup.py
Check that inside virtual environment, its possible to see the python package `setuptools-rust`:
```console
#
(.venv) #
(.venv) # pip list | grep setuptools-rust
setuptools-rust                1.10.2
(.venv) #
```
- - - 
If `python` is not used, `setup.py` has issues
```console
(.venv) # ./setup.py build_protobuf
Traceback (most recent call last):
File "/root/janitor/./setup.py", line 3, in <module>
from setuptools_rust import Binding, RustBin, RustExtension
ModuleNotFoundError: No module named 'setuptools_rust'
(.venv) #
(.venv) # python setup.py build_protobuf
/root/janitor/.venv/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
warnings.warn(msg, _BetaConfiguration)
usage: …
```
=> Shebangs: Support venv

pyproject.toml
```console
$ make PYTHON=python
[...]
python setup.py build_protobuf
/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
warnings.warn(msg, _BetaConfiguration)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help
error: invalid command 'build_protobuf'
make: *** [Makefile:10: build-inplace] Error 1
Error: Process completed with exit code 2.
```
=> Make Makefile happy (build_protobuf)

Dockerfile_site
```console
INFO:aiozipkin:Zipkin address was not provided, using stub transport
Traceback (most recent call last):
File "/usr/local/lib/python3.13/dist-packages/aiohttp/web_urldispatcher.py", line 562, in __init__
directory = Path(directory).expanduser().resolve(strict=True)
File "/usr/lib/python3.13/pathlib/_local.py", line 672, in resolve
return self.with_segments(os.path.realpath(self, strict=strict))
~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
File "<frozen posixpath>", line 445, in realpath
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/javascript/jquery-datatables'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/bin/janitor-site", line 8, in <module>
sys.exit(main())
~~~~^^
File …
```
=> Site: Add libjs-jquery-datatables

py/janitor/site/cupboard/__init__.py
Requesting: `/cupboard/broken-merge-proposals`
Errors with:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.13/dist-packages/aiohttp/web_protocol.py", line 480, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.13/dist-packages/aiohttp/web_app.py", line 569, in _handle
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.13/dist-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.13/dist-packages/janitor/site/openid.py", line 40, in openid_middleware
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.13/dist-packages/aiohttp_openmetrics/__init__.py", line 79, …
```
=> Fix PSQL for /cupboard/broken-merge-proposals

publish/src/bin/janitor-publish.rs
Related commit: e215bbc12c19a555c56ac9fa8083e88dfc77fd95
=> Rust: Publish - Drop un-used argument

py/janitor/runner.py
```
$ python3
Python 3.13.2 (main, Mar 13 2025, 14:29:07) [GCC 14.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import silver_platter
>>> print(silver_platter.pick_additional_colocated_branches)
<built-in function pick_additional_colocated_branches>
>>> print(silver_platter.invalid)
Traceback (most recent call last):
File "<python-input-3>", line 1, in <module>
print(silver_platter.invalid)
^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'silver_platter' has no attribute 'invalid'
>>>
```
=> Runner: silver_platter.debian -> silver_platter

src/logging.rs
Putting in `println!("Current log level: {:?}", log::max_level());` gave:
```
$ /code/target/release/janitor-worker   --credentials=/janitor/credentials.json     --base-url=http://runner:9911     --external-address=worker     --site-port=9821 --port=9821 --tee
[...]
Current log level: Info
$ /code/target/release/janitor-worker   --credentials=/janitor/credentials.json     --base-url=http://runner:9911     --external-address=worker     --site-port=9821 --port=9821 --tee --debug
[...]
Current log level: Error
```
=> Fix #1076: Fix --debug - Show more
